[settings]
install_before = "1d"

[tools]
"aqua:gastownhall/beads" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@anthropic-ai/sandbox-runtime" = "latest"
"npm:@just-every/code" = "latest"
"npm:@openai/codex" = "latest"
"npm:agent-browser" = "latest"
"npm:agmsg" = "latest"
"npm:beads-ui" = "latest"
"npm:yarn" = "latest"
"opencode" = "latest"
"rust" = "stable"

# [tools."npm:@openai/codex"]
# version = "latest"
# install_before = "0d"
